pipeline {
  agent any

  stages {
    stage('Install Helm Charts') {
      steps {
        sh '''
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo update

          helm upgrade --install prometheus prometheus-community/prometheus --namespace monitoring --create-namespace
          helm upgrade --install grafana grafana/grafana --namespace monitoring --create-namespace
          helm upgrade --install loki grafana/loki-stack --namespace monitoring --create-namespace
        '''
      }
    }
  }
}
